const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, apikey, authorization, x-t4u-token","Access-Control-Allow-Methods":"GET, OPTIONS"};
const BASE="https://ldmmphwivnnboyhlxipl.supabase.co";
const ANON="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkbW1waHdpdm5uYm95aGx4aXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxODA2MDUsImV4cCI6MjA3OTc1NjYwNX0.U2acfM5Ew7leACj4TWEy7EKwHi92270B1lt78dEjEfA";
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const ITEM_SELECT="id,name,category,condition,size,qty,location,avail,notes,tags,img,mkt,rent,sale,display_id,item_number,org_id";
const svcH=()=>({apikey:ANON,Authorization:`Bearer ${SERVICE||ANON}`});

async function pgGet(path:string,token?:string){
  const headers=token?{apikey:ANON,Authorization:`Bearer ${token}`}:svcH();
  const res=await fetch(`${BASE}/rest/v1/${path}`,{headers});
  if(!res.ok)return null;
  const rows=await res.json();
  return Array.isArray(rows)?rows:null;
}

async function rpc(fn:string,body:unknown){
  const res=await fetch(`${BASE}/rest/v1/rpc/${fn}`,{
    method:'POST',
    headers:{...svcH(),'Content-Type':'application/json'},
    body:JSON.stringify(body)
  });
  if(!res.ok)return null;
  return res.json();
}

async function buildResponse(item:Record<string,unknown>, req:Request){
  const orgId=item.org_id as string;
  const orgRows=await pgGet(`orgs?id=eq.${encodeURIComponent(orgId)}&select=id,name,email,phone,location,bio,qr_privacy,qr_contact_fields,label_prefix&limit=1`);
  const org=orgRows?.[0] as Record<string,unknown>|undefined;
  const privacy=(org?.qr_privacy as string)??"-contact";
  const contactFields=Array.isArray(org?.qr_contact_fields)?org.qr_contact_fields as string[]:["name","email"];

  const callerToken=(req.headers.get("x-t4u-token")||(req.headers.get("authorization")??"" ).replace(/^Bearer\s+/i,"")).trim();
  let isMember=false;
  if(callerToken&&callerToken!==ANON){
    const meRes=await fetch(`${BASE}/auth/v1/user`,{headers:{apikey:ANON,Authorization:`Bearer ${callerToken}`}});
    const me=meRes.ok?(await meRes.json() as Record<string,unknown>):null;
    const uid=me?.id as string|undefined;
    if(uid){
      const ownerRows=await pgGet(`orgs?id=eq.${encodeURIComponent(orgId)}&select=id&limit=1`,callerToken);
      if(ownerRows?.length)isMember=true;
      if(!isMember){
        const memRows=await pgGet(`org_members?org_id=eq.${encodeURIComponent(orgId)}&user_id=eq.${encodeURIComponent(uid)}&select=role&limit=1`);
        if(memRows?.length)isMember=true;
      }
    }
  }

  if(isMember||privacy==="public"){
    return {access:"full",item,org:{name:org?.name,location:org?.location,label_prefix:org?.label_prefix}};
  }

  const contactInfo:Record<string,unknown>={};
  if(org){
    if(contactFields.includes("name"))contactInfo.name=org.name;
    if(contactFields.includes("email"))contactInfo.email=org.email;
    if(contactFields.includes("phone"))contactInfo.phone=org.phone;
    if(contactFields.includes("location"))contactInfo.location=org.location;
    if(contactFields.includes("bio"))contactInfo.bio=org.bio;
  }
  return {access:"contact",item:{id:item.id,name:item.name,display_id:item.display_id},contact:contactInfo};
}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response(null,{status:200,headers:CORS});
  if(req.method!=="GET")return new Response("Method not allowed",{status:405,headers:CORS});

  const url=new URL(req.url);
  const itemId=(url.searchParams.get("id")||url.searchParams.get("code")||"").trim();
  if(!itemId)return new Response(JSON.stringify({error:"Missing id"}),{status:400,headers:{...CORS,"Content-Type":"application/json"}});

  const respond=(body:unknown,status=200)=>new Response(
    JSON.stringify(body),{status,headers:{...CORS,"Content-Type":"application/json"}}
  );

  // ── 1. UUID – standard format ──────────────────────────────────────────────
  const isUUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(itemId);
  if(isUUID){
    const rows=await pgGet(`items?id=eq.${encodeURIComponent(itemId)}&select=${ITEM_SELECT}`);
    if(rows?.length){
      const data=await buildResponse(rows[0] as Record<string,unknown>,req);
      return respond(data);
    }
    return respond({error:"Item not found"},404);
  }

  // ── 2. Short alphanumeric ID (e.g. 9f4s7huo3gi) — Theatre4u native IDs ────
  // Items generated by Theatre4u use short random IDs, not UUIDs.
  // QR codes encode: theatre4u.org/#/item/<short_id>
  const isShortId=/^[a-z0-9]{8,16}$/i.test(itemId);
  if(isShortId){
    const rows=await pgGet(`items?id=eq.${encodeURIComponent(itemId)}&select=${ITEM_SELECT}`);
    if(rows?.length){
      const data=await buildResponse(rows[0] as Record<string,unknown>,req);
      return respond(data);
    }
    // Don't return 404 yet — fall through to other checks
  }

  // ── 3. T4U-000001 legacy pool code ─────────────────────────────────────────
  if(/^T4U-\d{6}$/i.test(itemId)){
    const result=await rpc('lookup_label',{p_code:itemId.toUpperCase()});
    if(!result)return respond({error:"Label not found",pool_code:true},404);
    if(result.status==='claimed'&&result.item_id){
      const rows=await pgGet(`items?id=eq.${encodeURIComponent(result.item_id)}&select=${ITEM_SELECT}`);
      if(rows?.length){
        const data=await buildResponse(rows[0] as Record<string,unknown>,req);
        return respond({...data,pool_code:true,label_code:itemId});
      }
    }
    return respond({...result,pool_code:true,label_code:itemId});
  }

  // ── 4. OVHS-0001 style org pool code ──────────────────────────────────────
  if(/^[A-Z]{2,6}-\d{4}$/i.test(itemId)){
    const result=await rpc('lookup_label',{p_code:itemId.toUpperCase()});
    if(result){
      if(result.status==='claimed'&&result.item_id){
        const rows=await pgGet(`items?id=eq.${encodeURIComponent(result.item_id)}&select=${ITEM_SELECT}`);
        if(rows?.length){
          const data=await buildResponse(rows[0] as Record<string,unknown>,req);
          return respond({...data,pool_code:true,label_code:itemId});
        }
      }
      return respond({...result,pool_code:true,label_code:itemId});
    }
  }

  // ── 5. display_id – org-prefixed e.g. OVHS-COST-001 ────────────────────────
  const displayIdMatch=itemId.match(/^([A-Z]{2,6})-([A-Z]+-\d+)$/i);
  if(displayIdMatch){
    const orgPrefix=displayIdMatch[1].toUpperCase();
    const orgRows=await pgGet(`orgs?label_prefix=eq.${encodeURIComponent(orgPrefix)}&select=id&limit=1`);
    const orgId=orgRows?.[0]?.id as string|undefined;
    if(orgId){
      const rows=await pgGet(`items?org_id=eq.${encodeURIComponent(orgId)}&display_id=ilike.${encodeURIComponent(itemId)}&select=${ITEM_SELECT}&limit=1`);
      if(rows?.length){
        const data=await buildResponse(rows[0] as Record<string,unknown>,req);
        return respond(data);
      }
    }
  }

  // ── 6. Nothing matched ────────────────────────────────────────────────────
  return respond({error:"Item not found",legacy:true},404);
});
