// Static legal copy (Terms + Privacy) — extracted from App.jsx.
// Door aware: the brand name, site, contact email, Exchange name, audience,
// and pricing are resolved from config.js at load, so the same copy renders
// correctly on theatre4u.org (Theatre4u) and artstracker.org (ArtsTracker).
// The legal entity is always Artstracker LLC (it owns both brands).
import { IS_THEATRE4U, APP_NAME, APP_EMAIL, APP_HOST } from "./config.js";

const NAME     = APP_NAME;              // "Theatre4u™" or "ArtsTracker"
const EMAIL    = APP_EMAIL;             // hello@theatre4u.org or hello@artstracker.org
const HOST     = APP_HOST;              // theatre4u.org or artstracker.org
const EXCHANGE = IS_THEATRE4U ? "Backstage Exchange" : "The Exchange";

const SERVICE_DESC = IS_THEATRE4U
  ? "a cloud based inventory management, resource sharing, and community platform for theatre programs, schools, community theatres, and performing arts organizations"
  : "a cloud based inventory management, resource sharing, and community platform for theatre, music, dance, visual art, and other performing and visual arts programs, schools, and organizations";

const AUDIENCE = IS_THEATRE4U
  ? "theatre educators, school drama departments, community theatre organizations, and district administrators"
  : "arts educators, school arts departments (theatre, music, dance, and visual art), community arts organizations, and district administrators";

const PRICING = IS_THEATRE4U
  ? "Free, Pro ($15/month or $150/year), and District (from $49/month or $500/year) plans"
  : "Free, Pro ($59/month or $590/year), and District (from $199/month or $1,990/year) plans";

export const TERMS_CONTENT = [
  ["1. Acceptance of Terms",`By accessing or using ${NAME} at ${HOST}, you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service. ${NAME} is a product of Artstracker LLC, a California limited liability company (${HOST}).`],
  ["2. Description of Service",`${NAME} is ${SERVICE_DESC}. We reserve the right to modify or discontinue the Service at any time with reasonable notice.`],
  ["3. Account Registration","You must create an account with accurate information and are responsible for maintaining confidentiality of your credentials. You must be at least 18 years old, or have authorization of a parent, guardian, or school administrator if a minor acting on behalf of an organization."],
  ["4. Subscription Plans and Payments",`${NAME} offers ${PRICING} billed via Stripe. See the Plans page for current pricing and all District tiers. Subscriptions auto-renew unless cancelled. We may change pricing with 30 days notice to current subscribers.`],
  ["4a. Cancellation Policy",`You may cancel your subscription at any time through Settings, then Plans, then Manage Billing, or by emailing ${EMAIL}. Upon cancellation, your access continues until the end of the current billing period. No partial refunds are issued for unused time. For annual plans, a full refund is available within 30 days of purchase if you have added fewer than 10 items. After 30 days, annual plan fees are non-refundable. Your inventory data is preserved for 90 days after your plan downgrades to Free; you may export a full CSV backup at any time from the Reports page.`],
  ["5. User Content & License Grant",`You retain all ownership of content you upload to ${NAME}, including text, photos, images, and other materials ('User Content'). By uploading User Content, you grant ${NAME} a worldwide, non-exclusive, royalty-free, perpetual, irrevocable license to store, display, reproduce, and use that content to operate, improve, and promote the Service. This license persists even if you later remove the content or close your account. You represent that you have all necessary rights to grant this license, that your content does not infringe any third-party rights, and that you have obtained appropriate permissions for any photographs or images of identifiable individuals. ${NAME} may remove any content that violates these Terms or applicable law.`],
  ["6. Exchange Transactions",`${NAME} provides the ${EXCHANGE} platform for listing items for rent, sale, or loan. We are not a party to any transaction between users. All agreements are solely between listing users and interested parties. We do not handle payments between users.`],
  ["7. Prohibited Conduct","You agree not to: use the Service unlawfully; upload false or fraudulent content; attempt unauthorized access; interfere with the Service; use automated scraping tools; impersonate others; or transmit spam or malware. Violations may result in immediate account termination."],
  ["8. Intellectual Property",`The ${NAME} name, logo, design, software, and all platform content are owned by Artstracker LLC and protected by United States and international intellectual property laws. ${NAME} is a trademark of Artstracker LLC. Nothing in these Terms grants you any right to use our trademarks, trade names, or other intellectual property without prior written consent. All rights not expressly granted are reserved.`],
  ["9. Disclaimer of Warranties","THE SERVICE IS PROVIDED AS IS WITHOUT WARRANTIES OF ANY KIND. We do not warrant that the Service will be uninterrupted, error-free, or free of harmful components."],
  ["10. Limitation of Liability","TO THE FULLEST EXTENT PERMITTED BY CALIFORNIA LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES. Our total liability shall not exceed amounts paid by you in the three months preceding the claim."],
  ["11. Governing Law","These Terms are governed by California law. Disputes shall be resolved through binding arbitration in California under AAA rules, except either party may seek injunctive relief in court. You waive the right to class action."],
  ["12. Changes & Contact",`We may modify these Terms with 14 days notice. Continued use constitutes acceptance. Questions: ${EMAIL} | Artstracker LLC, California, USA`],
];

export const PRIVACY_CONTENT = [
  ["1. Introduction", `${NAME} (${HOST}) is a product of Artstracker LLC, a California limited liability company. We are committed to protecting the privacy and security of all users, with special attention to the requirements applicable to educational institutions and school districts. This Privacy Policy complies with the California Consumer Privacy Act (CCPA), CalOPPA, the Family Educational Rights and Privacy Act (FERPA), and the Children's Online Privacy Protection Act (COPPA).`],
  ["2. Who Uses This Service", `${NAME} is designed for use by ${AUDIENCE}. Users must be 18 years or older to create an account. ${NAME} is not intended for direct use by students under 18. School administrators and teachers are responsible for ensuring appropriate use within their programs.`],
  ["3. Information We Collect", "Account Information: organization name, email address, password (encrypted via Supabase Auth, so we never see plaintext passwords), and optional profile details including phone, city, and bio. Inventory Data: item names, descriptions, photos, locations, and condition notes you add to your account. Communication Data: messages sent between organizations on the platform. Usage Data: pages visited and features used, to improve the platform. We do NOT collect student personally identifiable information (PII). All data belongs to your organization."],
  ["4. How We Use Your Information", `To provide and operate the ${NAME} platform. To facilitate ${EXCHANGE} listings and rental/loan requests between programs. To send transactional emails (request notifications, account confirmation) via Resend from ${EMAIL}. To improve the platform based on anonymized usage patterns. We do NOT sell your data. We do NOT use your data for advertising. We do NOT share your data with third parties except as described in section 5.`],
  ["5. Data Sharing & Third Parties", `Supabase (supabase.com): Our database and authentication provider, hosted in AWS us-east-1. All data is encrypted at rest and in transit. Supabase is SOC 2 Type II certified. Resend (resend.com): Transactional email delivery only. Vercel (vercel.com): Web hosting and CDN. No user data is stored by Vercel. Stripe (stripe.com): Payment processing for subscriptions only. Stripe does not receive inventory or student data. Other Programs: When you post items to ${EXCHANGE}, your organization name, location, and listed items are visible to other logged-in ${NAME} members. No other sharing occurs.`],
  ["6. FERPA Compliance", `${NAME} acknowledges its role as a service provider to educational institutions subject to FERPA. ${NAME} does not collect, store, or process student education records as defined by FERPA. All inventory and operational data belongs to the subscribing organization (the school or district), not to individual students. School administrators retain full control over their organizational data and may request complete data deletion at any time. ${NAME} will not disclose organizational data to third parties without the written consent of the institution's authorized representative, except as required by law.`],
  ["7. Student Privacy (COPPA)", `${NAME} accounts are for adults only (18+). If you believe a minor has created an account without authorization, contact ${EMAIL} immediately and we will delete the account and all associated data within 48 hours. ${NAME} does not knowingly collect personal information from children under 13.`],
  ["8. Data Security", "All data is encrypted in transit via TLS 1.2+. Database data is encrypted at rest via AES-256 (Supabase/AWS). Passwords are hashed using bcrypt, so we cannot access your password. Authentication tokens expire automatically. Row-Level Security (RLS) is enforced on all database tables, so each organization can only access its own data. Security headers (HSTS, CSP, X-Frame-Options) are enforced on all pages. The anon key exposed in the client is restricted by RLS policies and cannot access other organizations' private data."],
  ["9. Data Retention & Deletion", `Your data is retained as long as your account is active. You may request complete deletion of your account and all associated data at any time by emailing ${EMAIL}. We will complete deletion within 30 days. Deleted data is not recoverable. Anonymized aggregate statistics (total item counts, etc.) may be retained. Backup snapshots are retained for 7 days before permanent deletion.`],
  ["10. Your Rights (CCPA)", `California residents have the right to: know what personal data we collect and how it is used; request deletion of your data; opt out of sale of personal data (we do not sell data); non-discrimination for exercising privacy rights. To exercise any right: email ${EMAIL} with 'Privacy Request' in the subject line.`],
  ["11. District Data Agreements", `For school district subscribers (District plan), Artstracker LLC will execute a Data Processing Agreement (DPA) upon request. Contact ${EMAIL}. We will cooperate with district IT security reviews and questionnaires. Our infrastructure (Supabase/Vercel) can provide SOC 2 and ISO 27001 documentation upon request for your district's vendor review process.`],
  ["12. Changes & Contact", `We will notify users of material changes to this policy with at least 14 days notice via email. Questions, data requests, or security concerns: ${EMAIL} | ${HOST} | Artstracker LLC, California, USA. For security vulnerabilities, please email ${EMAIL} with 'Security' in the subject line.`],
];
