// Static legal copy (Terms + Privacy) — extracted from App.jsx.
// Door aware: the brand name, site, contact email, Exchange name, audience,
// and pricing are resolved from config.js at load, so the same copy renders
// correctly on theatre4u.org (Theatre4u) and artstracker.org (ArtsTracker).
// The legal entity is always Artstracker LLC (it owns both brands).
import { IS_THEATRE4U, APP_NAME, APP_EMAIL, APP_HOST } from "./config.js";

const NAME     = APP_NAME;              // "Theatre4u™" or "ArtsTracker"
const EMAIL    = APP_EMAIL;             // hello@theatre4u.org or hello@artstracker.org
const HOST     = APP_HOST;              // theatre4u.org or artstracker.org
const EXCHANGE = IS_THEATRE4U ? "Backstage Exchange" : "The Exchange";

const SERVICE_DESC = IS_THEATRE4U
  ? "a cloud based inventory management, resource sharing, and community platform for theatre programs, schools, community theatres, and performing arts organizations"
  : "a cloud based inventory management, resource sharing, and community platform for theatre, music, dance, visual art, and other performing and visual arts programs, schools, and organizations";

const AUDIENCE = IS_THEATRE4U
  ? "theatre educators, school drama departments, community theatre organizations, and district administrators"
  : "arts educators, school arts departments (theatre, music, dance, and visual art), community arts organizations, and district administrators";

const PRICING = IS_THEATRE4U
  ? "Free, Pro ($15/month or $150/year), and District (from $49/month or $500/year) plans"
  : "Free, Pro ($59/month or $590/year), and District (from $199/month or $1,990/year) plans";

export const TERMS_CONTENT = [
  ["1. Acceptance of Terms",`By accessing or using ${NAME} at ${HOST}, you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service. ${NAME} is a product of Artstracker LLC, a California limited liability company (${HOST}).`],
  ["2. Description of Service",`${NAME} is ${SERVICE_DESC}. We reserve the right to modify or discontinue the Service at any time with reasonable notice.`],
  ["3. Account Registration and Eligibility",`You must create an account with accurate information and are responsible for keeping your credentials confidential. Accounts must be created by adults (18 or older) or by school employees authorized to act on behalf of their organization. ${NAME} is intended for educators, administrators, and program leaders, not for direct signup by students. Where a program gives students access, that access is provisioned and controlled by the school or organization that holds the account, and that organization is responsible for obtaining any parental or guardian consent required by law.`],
  ["4. Subscription Plans and Payments",`${NAME} offers ${PRICING} billed via Stripe. See the Plans page for current pricing and all District tiers. Paid subscriptions begin September 1, 2026; accounts created during the beta period receive founding member pricing as described on the Plans page. Subscriptions renew automatically at the rate then in effect for your billing cycle (monthly or annual) until you cancel. We will send advance email notice before an annual renewal and before any price increase. You may cancel at any time online through Settings without contacting us. We may change pricing with 30 days notice to current subscribers.`],
  ["4a. Cancellation Policy",`You may cancel your subscription at any time through Settings, then Plans, then Manage Billing, or by emailing ${EMAIL}. Upon cancellation, your access continues until the end of the current billing period. Monthly plan fees are not refundable for the current period. For annual plans, you may request a full refund within 30 days of your initial purchase; after 30 days, annual plan fees are non-refundable, except where required by law. Your inventory data is preserved for 90 days after your plan downgrades to Free; you may export a full CSV backup at any time from the Reports page.`],
  ["5. Your Content and License Grant",`You retain all ownership of content you upload to ${NAME}, including text, photos, images, program and student records, and other materials ('Customer Content'). You grant ${NAME} a limited, nonexclusive, royalty free license to host, store, process, reproduce, and display Customer Content solely as needed to provide, secure, support, and improve the Service for you. This license ends when you delete the content or close your account, except for backup copies retained for a limited period as described in our Privacy Policy and any records we must keep to comply with law. We will not use Customer Content in advertising or public promotional materials without your separate written permission. You represent that you have all rights needed to grant this license, that your content does not infringe the rights of others, and that you have obtained the permissions and consents required for any photographs, images, or records of identifiable individuals, including students or minors. ${NAME} may remove content that violates these Terms or applicable law.`],
  ["6. Exchange Transactions",`${NAME} provides the ${EXCHANGE} platform for listing items for rent, sale, or loan. We are not a party to any transaction between users. All agreements are solely between listing users and interested parties. We do not handle payments between users.`],
  ["7. Acceptable Use and Prohibited Conduct",`You agree to use ${NAME} only for lawful purposes and only to manage your program or organization. You agree not to: use the Service in violation of any law; upload, store, or share content that is illegal, fraudulent, harassing, threatening, hateful, or defamatory; upload sexually explicit material, nudity, or any content that sexualizes a minor; upload images or personal information of any person, including students, without the permissions and consents required by law; upload content you do not have the right to share or that infringes the rights of others; attempt unauthorized access; interfere with or disrupt the Service; use automated scraping tools or bots; impersonate others; or transmit spam, malware, or harmful code. You are responsible for the conduct of everyone you invite to your account, and account administrators are responsible for supervising their team members and students. We may review, remove, or disable access to any content, and may suspend or terminate any account, at any time and without prior notice, if we believe these Terms or applicable law have been violated. We report apparent child sexual abuse material to the National Center for Missing and Exploited Children (NCMEC) as required by law.`],
  ["8. Intellectual Property",`The ${NAME} name, logo, design, software, and all platform content are owned by Artstracker LLC and protected by United States and international intellectual property laws. ${NAME} is a trademark of Artstracker LLC. Nothing in these Terms grants you any right to use our trademarks, trade names, or other intellectual property without prior written consent. All rights not expressly granted are reserved.`],
  ["9. Disclaimer of Warranties","THE SERVICE IS PROVIDED AS IS WITHOUT WARRANTIES OF ANY KIND. We do not warrant that the Service will be uninterrupted, error-free, or free of harmful components."],
  ["10. Limitation of Liability","TO THE FULLEST EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES. Except where prohibited by law, our total liability for any claim is limited to the amounts you paid us for the Service in the twelve months before the claim. For school and district customers, a signed district agreement, order form, or Data Processing Agreement controls and may set different liability terms, which govern over this section."],
  ["11. Governing Law and Disputes",`These Terms are governed by California law. Most disputes will be resolved by binding arbitration in California, on an individual basis, and you and we waive the right to a jury trial and to participate in a class action. Either party may still bring a qualifying claim in small claims court, and either party may seek injunctive relief in court. You may opt out of arbitration by emailing ${EMAIL} within 30 days of first accepting these Terms. Government and public entities, including school districts, are not bound by the arbitration or class action waiver to the extent applicable law does not permit them; those disputes proceed as allowed by law, and any signed district agreement controls.`],
  ["12. Changes & Contact",`We may update these Terms from time to time. Changes apply going forward; we will post the updated Terms with a new date and, for material changes, provide at least 14 days notice by email or within the Service. Your continued use after the changes take effect means you accept them. For customers with a signed school or district agreement, that agreement's amendment terms control. Questions: ${EMAIL} | Artstracker LLC, California, USA`],
];

export const PRIVACY_CONTENT = [
  ["1. Introduction", `${NAME} (${HOST}) is a product of Artstracker LLC, a California limited liability company. We are committed to protecting the privacy and security of all users, with special attention to the requirements applicable to educational institutions and school districts. This Privacy Policy is designed to address the requirements that may apply to us and to our educational customers, including the California Consumer Privacy Act (CCPA), CalOPPA, the Family Educational Rights and Privacy Act (FERPA), and the Children's Online Privacy Protection Act (COPPA).`],
  ["2. Who Uses This Service", `${NAME} is designed for use by ${AUDIENCE}. Accounts are created by adults (18 or older) or by authorized school employees, not by students directly. Where a program gives students access (for example, team members added by a teacher, or a join code), that access is set up and controlled by the school or organization that holds the account. The account holder acts as the data controller for any student information and is responsible for consents required by law.`],
  ["3. Information We Collect", "Account Information: organization name, email address, password (encrypted via Supabase Auth, so we never see plaintext passwords), and optional profile details including phone, city, and bio. Inventory Data: item names, descriptions, photos, locations, and condition notes you add to your account. Communication Data: messages sent between organizations on the platform. Usage Data: pages visited and features used, which we use to operate and improve the platform. Cookies and Tracking Technologies: across our websites and web app, we and our providers use cookies and similar technologies, including Google Analytics and the Meta (Facebook) Pixel, to understand how visitors and users interact with the Service, to measure the performance of our advertising, and to record when a visit leads to a signup. These tools may collect device and usage identifiers and IP address through cookies; they do not receive your account credentials, inventory, messages, or student or organizational content. You can control cookies in your browser settings, opt out of Google Analytics at tools.google.com/dlpage/gaoptout, and manage interest-based ads at aboutads.info/choices. This Service is built for program administration, not for collecting information about students; any student information we process belongs to your organization, as described in the Student Data section."],
  ["4. How We Use Your Information", `To provide and operate the ${NAME} platform. To facilitate ${EXCHANGE} listings and rental/loan requests between programs. To send transactional emails (request notifications, account confirmation) via Resend from ${EMAIL}. To operate and improve the platform based on usage patterns. Across our websites and web app we use standard analytics and advertising measurement tools (Google Analytics and the Meta Pixel) to understand how people find and use the Service and whether a visit leads to a signup, so we can run and improve our advertising. These tools may collect device and usage identifiers and IP address, but we never send them your account information, inventory, messages, or any student or district content, and we do NOT sell your data. We do NOT share your data with third parties except as described in section 5.`],
  ["5. Data Sharing & Third Parties", `Supabase (supabase.com): Our database and authentication provider, hosted in AWS us-east-1. All data is encrypted at rest and in transit. Supabase is SOC 2 Type II certified. Resend (resend.com): Transactional email delivery only. Vercel (vercel.com): Web hosting and content delivery. Vercel processes web requests to serve the Service and keeps standard server and CDN logs (such as IP address and request metadata); it does not store your account or inventory content. Stripe (stripe.com): Payment processing for subscriptions only. Stripe does not receive inventory or student data. Google Analytics & Meta (Facebook) Pixel: analytics and advertising measurement across our websites and web app (page views, referral source, signup events, and device or usage identifiers collected through cookies), used to run and measure our advertising. These tools do not receive your inventory, messages, or organizational content. Other Programs: When you post items to ${EXCHANGE}, your organization name, location, and listed items are visible to other logged-in ${NAME} members. No other sharing occurs.`],
  ["6. Student Data and FERPA", `${NAME} is built for program administration, not for collecting information about students. Depending on how your organization uses the Service, limited student information may be processed on your behalf, such as a name or school email for a student team member, or a photo or record that your staff uploads. Any such information belongs to the subscribing organization (the school or district), which acts as the data controller; ${NAME} acts as a service provider under the FERPA school official exception where applicable. We use student information only to provide the Service to your organization. We do not sell student information, do not use it for targeted advertising, and do not build student profiles for purposes unrelated to the school. School administrators retain full control over their organization's data and may request export or complete deletion at any time. ${NAME} will not disclose organizational data to third parties without the written consent of the institution's authorized representative, except as required by law.`],
  ["7. Children's Privacy (COPPA)", `${NAME} is not directed to children and does not offer public signup to students. Student access, where a program chooses to enable it, is provisioned and supervised by the school under the school's authority. For students under 13, a school's authorization under COPPA covers school authorized educational use only and does not replace parental consent for any commercial use; ${NAME} does not use student information for commercial purposes. If you believe a child created an account through ordinary public signup without school authorization, contact ${EMAIL} and we will remove it and any associated data promptly.`],
  ["8. Data Security", "All data is encrypted in transit via TLS 1.2+. Database data is encrypted at rest via AES-256 (Supabase/AWS). Passwords are hashed using bcrypt, so we cannot access your password. Authentication tokens expire automatically. Row-Level Security (RLS) is enforced on all database tables, so each organization can only access its own data. Security headers (HSTS, CSP, X-Frame-Options) are enforced on all pages. The anon key exposed in the client is restricted by RLS policies and cannot access other organizations' private data."],
  ["9. Data Retention & Deletion", `Your data is retained as long as your account is active. You may request complete deletion of your account and all associated data at any time by emailing ${EMAIL}. We will complete deletion within 30 days. Deleted data is not recoverable. Anonymized aggregate statistics (total item counts, etc.) may be retained. Backup snapshots are retained for 7 days before permanent deletion.`],
  ["10. Your Rights (CCPA)", `California residents have the right to: know what personal data we collect and how it is used; request deletion of your data; opt out of sale of personal data (we do not sell data); non-discrimination for exercising privacy rights. To exercise any right: email ${EMAIL} with 'Privacy Request' in the subject line.`],
  ["11. District Data Agreements", `For school district subscribers (District plan), Artstracker LLC will execute a Data Processing Agreement (DPA) upon request. Contact ${EMAIL}. We will cooperate with district IT security reviews and questionnaires. Our infrastructure (Supabase/Vercel) can provide SOC 2 and ISO 27001 documentation upon request for your district's vendor review process.`],
  ["12. Changes & Contact", `We will notify users of material changes to this policy with at least 14 days notice via email. Questions, data requests, or security concerns: ${EMAIL} | ${HOST} | Artstracker LLC, California, USA. For security vulnerabilities, please email ${EMAIL} with 'Security' in the subject line.`],
];
